### ISSUE TITLE
no data yet?

### ISSUE THREAD

**Issue by sjgenco** [jamesmartherus/anesr#1]
I recently started doing some work with the ANES surveys and was excited to see this handy way to access the various datasets in R. However, I just followed your README installation instructions and everything seemed to go well up to the actual data(dataset_name) command, which failed. Here's my jupyterlab notebook:

![image](https://user-images.githubusercontent.com/19754884/118376182-42b9a680-b57b-11eb-93e6-1ebdc242a2a4.png)

The commented-out commands ran successfully per your README. The `data(package="anesr")` command then worked as expected, listing 46 packages (collapsed in this screenshot), but as you can see, the data commands for both datasets and docs produced a `“data set ‘timeseries_2016’ not found”` response.

Is the data not there yet? or maybe there is a step in the process I've left out?

**Comment by jamesmartherus** [comment]
Hmm. I'm unable to reproduce your error, it may be related to using an iPython notebook. Can you try running it with parentheses (e.g., data("timeseries_2016"))? If that doesn't work, I don't think I have a short term fix. Are you able to use RStudio?

**Comment by sjgenco** [comment]
Thank you for the quick response! First, I tried putting the dataset name in quotes, got the same result. So I installed RStudio in my Anaconda R environment, ran the commands, and everything worked like a charm. So the problem appears to be specific to trying to access the data thru Jupyter Lab. If you want to try to replicate, here are the basics of my environment:

- MacBook Pro 16
- 8-Core Intel Core i9 2.3Ghz 8 cores
- Memory:	16 GB
- MacOS Big Sur 11.3.1
- Chrome version 90.0.4430.212 (Official Build) (x86_64)
- Security software: McAfee Total Protection 4.11.1.0 (1012)
- Anaconda 2.0.3 with a dedicated R environment (r_env)
- Jupyter Lab 3.0.15 launched in Chrome from Anaconda r_env, R kernel, ran this sequence of commands:
`install.packages("devtools")`
`library(devtools)`
`install_github("jamesmartherus/anesr")`
`data(package="anesr")`   <-- the list of files appears as expected
`data(pilot_2018)`   <-- this returns nothing
`data("pilot_2018")`   <-- this also returns nothing

If this sequence doesn't replicate the issue for you, the problem must be deeper in my setup. I have run other R programs in this environment and they worked as expected. If you need more info from me to research this, just ask.

Thanks again for making these datasets available in R. I'll continue my work from here in RStudio.
