### ISSUE TITLE
Filter Error with Time Series 2020 Data

### ISSUE THREAD

**Issue by alexlevit** [jamesmartherus/anesr#2]
Hi there,

Ran into the following issue when filtering the timeseries_2020 data. I had no issues using the cumulative time series file with what were essentially the same commands.

After loading up dplyr, devtools, and anesr, I ran the following commands:

`data(timeseries_2020)
datadems2020 <- timeseries_2020 %>% filter(V201228 == 1)` 

This resulted in the following:

![See Screenshot](https://user-images.githubusercontent.com/72096708/157153390-a16e229e-df60-44c2-b2f2-32caadef2212.png)

That being said, anything that involves playing with the data seems to result in that same error:

![Screenshot](https://user-images.githubusercontent.com/72096708/157154507-72165182-b29e-4e51-b708-ea8c29337306.png)

This could very well be user error, I am quite rusty when it comes to R, but reaching out in case it is a data or package issue. 

Thank you.

**Comment by jamesmartherus** [comment]
Hi Alex, this is because most variables are given the `haven_labelled` class. This lets us store metadata like the text of the survey question. You can fix the error by loading the haven package.
